In [1]:
import numpy as np
import matplotlib.pyplot as plt

import os
import cv2

from PIL import Image

from tensorflow import keras
import tensorflow.keras.layers as k

from tqdm.notebook import tqdm
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

/Users/aasthaahlawat/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
classifier=cv2.CascadeClassifier('/Users/aasthaahlawat/Documents/CNN/haarcascade_frontalface_default.xml')

cam=cv2.VideoCapture(0)

while True:
    _,img=cam.read()
    img=cv2.flip(img,1)
    
    try:
     faces=classifier.detectMultiScale(img,2.1,1)
     for(x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,180,0),2)
    except:
       pass

    
    cv2.imshow("Frame",img)
    
    print(faces)
    print('*'*100)

    
    key=cv2.waitKey(30)

    if(key==27):
        cam.release()
        cv2.destroyAllWindows()  
        break

()
****************************************************************************************************
[[744 375 467 467]]
****************************************************************************************************
[[745 376 467 467]]
****************************************************************************************************
[[739 389 467 467]]
****************************************************************************************************
[[748 380 467 467]
 [541 550  50  50]
 [541 569  50  50]]
****************************************************************************************************
()
****************************************************************************************************
()
****************************************************************************************************
()
****************************************************************************************************
()
***********************************************************

SHOWING THE LARGEST FACE AS A SEPERATE FRAME

In [3]:
classifier=cv2.CascadeClassifier('/Users/aasthaahlawat/Documents/CNN/haarcascade_frontalface_default.xml')

cam=cv2.VideoCapture(0)

while True:
    is_image,img=cam.read()

    if not is_image:
        break
       
    img=cv2.flip(img,1)

    faces=classifier.detectMultiScale(img,1.1,5)
    print(faces)

    if(len(faces)>=1):
        largest_face=max(faces,key=lambda f:f[2]*f[3])
        x,y,w,h=largest_face

        cv2.rectangle(img,(x,y),(x+w,y+h),(0,180,0),2)
        face=img[y:y+h,x:x+w]
        cv2.imshow("Face",face)
    
    cv2.imshow("Frame",img)

    key=cv2.waitKey(30)

    if(key==27):
        cam.release()
        cv2.destroyAllWindows()  
        break

()
[[532 238 613 613]]
[[526 227 626 626]]
[[534 235 609 609]]
[[530 232 616 616]]
[[521 228 626 626]]
[[522 225 629 629]]


BLUR THE FACE

In [4]:
classifier=cv2.CascadeClassifier('/Users/aasthaahlawat/Documents/CNN/haarcascade_frontalface_default.xml')

cam=cv2.VideoCapture(0)

while True:
    is_image,img=cam.read()

    if not is_image:
        break
       
    img=cv2.flip(img,1)

    faces=classifier.detectMultiScale(img,1.1,5)
    print(faces)

    if(len(faces)>=1):
        largest_face=max(faces,key=lambda f:f[2]*f[3])
        x,y,w,h=largest_face

        cv2.rectangle(img,(x,y),(x+w,y+h),(0,180,0),2)
        face=img[y:y+h,x:x+w]
        face=cv2.blur(face,(32,32))
        img[y:y+h,x:x+w]=face
        cv2.imshow("Face",face)
    
    cv2.imshow("Frame",img)

    key=cv2.waitKey(30)

    if(key==27):
        cam.release()
        cv2.destroyAllWindows()  
        break

()
[[536 229 620 620]]
[[548 238 602 602]]
[[536 228 626 626]]
[[524 220 637 637]]
[[527 223 643 643]]


RECTANGLE ON FACE

In [5]:
classifier=cv2.CascadeClassifier('/Users/aasthaahlawat/Documents/CNN/haarcascade_frontalface_default.xml')

cam=cv2.VideoCapture(0)

while True:
    is_image,img=cam.read()

    if not is_image:
        break
       
    img=cv2.flip(img,1)

    faces=classifier.detectMultiScale(img,1.1,5)
    print(faces)

    if(len(faces)>=1):
        largest_face=max(faces,key=lambda f:f[2]*f[3])
        x,y,w,h=largest_face


        cv2.rectangle(img,(x,y),(x+w,y+h),(0,180,0),2)
        face=img[y:y+h,x:x+w]
        black=np.zeros(face.shape,dtype=int)
        
        img[y:y+h,x:x+w]=black
        cv2.imshow("Face",face)
    
    cv2.imshow("Frame",img)

    key=cv2.waitKey(30)

    if(key==27):
        cam.release()
        cv2.destroyAllWindows()  
        break

()
[[516 216 658 658]]
[[525 219 647 647]]
[[521 224 645 645]]
[[509 231 664 664]]
[[504 229 667 667]]
[[505 214 656 656]]
[[512 225 665 665]]
[[495 217 676 676]]
[[500 217 668 668]]
[[498 228 665 665]]
[[508 232 669 669]]
[[510 225 660 660]]
[[549 241 602 602]]
[[529 229 643 643]]
[[546 226 595 595]]
[[541 214 617 617]]
[[555 225 575 575]]
[[557 230 566 566]]
[[569 244 539 539]]
[[577 263 515 515]]
[[572 267 505 505]]
[[578 281 496 496]]


CIRCLE ON FACE

In [6]:
classifier=cv2.CascadeClassifier('/Users/aasthaahlawat/Documents/CNN/haarcascade_frontalface_default.xml')

cam=cv2.VideoCapture(0)

while True:
    is_image,img=cam.read()

    if not is_image:
        break
       
    img=cv2.flip(img,1)

    faces=classifier.detectMultiScale(img,1.1,5)
    print(faces)

    if(len(faces)>=1):
        largest_face=max(faces,key=lambda f:f[2]*f[3])
        x,y,w,h=largest_face

        circle_x=x+int(w/2)
        circle_y=y+int(h/2)

        cv2.circle(img,(circle_x,circle_y),200,(0,180,0),-1)
        face=img[y:y+h,x:x+w]
        
        img[y:y+h,x:x+w]=face
        cv2.imshow("Face",face)
    
    cv2.imshow("Frame",img)

    key=cv2.waitKey(30)

    if(key==27):
        cam.release()
        cv2.destroyAllWindows()  
        break

()
[[586 299 475 475]]
[[589 299 469 469]]
[[590 294 476 476]]
[[587 293 479 479]]
[[591 294 476 476]]
[[591 292 481 481]]
[[587 294 489 489]]
[[584 289 492 492]]
[[577 287 497 497]]
[[577 289 492 492]]
[[570 279 505 505]]
[[568 279 503 503]]


SAVE ALL FACES ENCOUNTERED

In [7]:
classifier=cv2.CascadeClassifier('/Users/aasthaahlawat/Documents/CNN/haarcascade_frontalface_default.xml')

cam=cv2.VideoCapture(0)

def save(frame,folder):
        if not os.path.exists(folder):
          os.makedirs(folder)
        name_img=len(os.listdir(folder))+1
        name_img=folder+'/IMG'+str(name_img)+'.png'
        cv2.imwrite(name_img,frame)
        print(name_img,'is exported')

while True:
    is_image,img=cam.read()

    if not is_image:
        break
       
    img=cv2.flip(img,1)

    faces=classifier.detectMultiScale(img,1.1,5)
    print(faces)

    key = cv2.waitKey(30) & 0xFF


    for x,y,w,h in faces:

        face=img[y:y+h,x:x+w]
        cv2.imshow("Face",face)
        
        if(key==13):
            save(face,'People')
        elif(key==127):
            pass
        
    
    cv2.imshow("Frame",img)

    if(key==27):
        cam.release()
        cv2.destroyAllWindows()  
        break

()
[[563 264 514 514]]
[[569 264 507 507]]
[[568 252 526 526]]
[[573 247 525 525]]
[[582 239 529 529]]
[[579 233 545 545]]
[[580 222 559 559]]
[[581 203 564 564]]
[[580 199 575 575]]
[[580 180 602 602]]
[[581 183 594 594]]
[[583 190 602 602]]
[[571 189 629 629]]
[[588 207 595 595]]
[[572 204 623 623]]
[[568 201 635 635]]
[[562 206 646 646]]
[[566 209 633 633]]
[[541 195 678 678]]
[[556 216 644 644]]
[[562 217 642 642]]
[[574 231 615 615]]
[[561 234 641 641]]
[[537 217 673 673]]
[[552 248 642 642]]
[[547 247 637 637]]
[[512 217 700 700]]
[[518 210 701 701]]
[[519 215 699 699]]
[[488 206 729 729]]
[[536 224 653 653]]
[[545 230 640 640]]
[[541 221 641 641]]
[[537 225 642 642]]
[[530 236 632 632]]
[[542 255 611 611]]
[[531 250 622 622]]
[[536 252 610 610]]
[[537 252 603 603]]
[[538 254 605 605]]
[[540 249 609 609]]
[[540 250 606 606]]
[[538 256 616 616]]
[[539 247 614 614]]
[[517 245 646 646]]
[[521 251 640 640]]
[[539 258 615 615]]
[[539 256 628 628]]
[[518 253 650 650]]
[[530 251 637 637